apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devops-it-mailu-certificates
spec:
  secretName: devops-it-mailu-certificates
  renewBefore: 1440h0m0s
  commonName: "sanatorioallende.com.ar"
  dnsNames:
  - "mail.sanatorioallende.com.ar"
  - "imap-sanatorioallende.com.ar"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt